### ISSUE TITLE
Shortcut for all users fail

### ISSUE THREAD

**Issue by ale5000-git** [kiwi0fruit/shortcutter#15]
I'm trying to install a shortcut for all users on Ubuntu but it fails; I'm trying with these commands:
```
sudo pip3 install --no-user --upgrade-strategy eager -U youtube-dl tartube
sudo shortcutter -m -n Tartube -s tartube
```

**Comment by kiwi0fruit** [comment]
Without output of the shortcutter and results of it's work it's hard to start examining this issue.

**Comment by kiwi0fruit** [comment]
But I guess it's too late for extra details. Closing.

**Comment by kiwi0fruit** [comment]
General recommendation is to check that desired executables are in the $PATH
