### ISSUE TITLE
Support for icons, arguments, improved GUI macOS apps

### ISSUE THREAD

**Issue by newville** [kiwi0fruit/shortcutter#3]
I asked a similar question at the upstream repo (https://github.com/martinohanlon/shortcut/issues/19), but I'm not entirely sure where development stands. I have some scripts for making shortcuts for apps at  https://github.com/newville/pyshortcuts/blob/master/pyshortcuts/pyshortcuts.py

These are simple, and so may seem somewhat less well-designed than the interface here.  
But I see a couple missing features with the current version of `shortcutter`:

-   specify an icon file to use.
-   better support for non-terminal Apps for MacOS.   

If you are interested the code in `pyshortcuts.py` to help implement these, please feel free to use tham as you see fit.  If you would like to see a PR, please let me know.

**Comment by kiwi0fruit** [comment]
If you would make a PR it would be great. I myself do not have access to a macOS so I cannot really test it. So it would be great if you help to improve macOS experience.

And I guess it would be easy to add shortcuts support. But there should be decided what UI should be except python API: as I see it on Windows: by default shortcutter takes icon from target (and even uses it with activation wrapper script - that is not happening now). But it can also be set via -i or --icon.

**Comment by newville** [comment]
@kiwi0fruit  Oh, I thought this was meant to be cross-platform?  Looking at the code here, it looks like adding an option for icons would require touching a fair amount of code, which sort of surprises me.   To be clear, my need and intention is to be able to make shortcuts for python scripts, which will not have icons in them, and need to have a separate icon file specified.

For the time being, I may just focus on my `pyshortcuts` code and see how far that gets, and then consider a PR to this at some later point.  That said, if you want to use any of the code there, please feel free to do so.  Cheers!

**Comment by kiwi0fruit** [comment]
I guess shortcutter is cross-platform (as it's a fork of cross-platform
"shortcut"). I test in on Windows and latest Ubuntu and I didn't really
changed macOS code from "shortcut" - but it still
needs testing on macOS (theoretically it should be OK on macOS but I'd
prefer to test it practically).

You need to modify three ways of creating shortcuts: Windows, Linux, macOS.
Then add interface and arguments forwarding.

If you change Linux and macOS behavior (add icons) I would add it for
Windows, add interface and arguments forwarding.

**Comment by newville** [comment]
@kiwi0fruit @martinohanlon I'm not sure if you are interested, but I've put some more work into a similar package (https://github.com/newville/pyshortcuts/ ) for making desktop shortcuts for python scripts and apps.  This is now released and available on PyPI.  With this package,  shortcuts to python scripts and programs can be made from very simple pythons scripts, or from a command-line program, or from a simple GUI form that can generate either a python generating script (as for post-installation processes) or directly making a shortcut.    It does support both setting an icon for the shortcut and supports command-line arguments to be passed to the script.   

If any of the code there is of interest to you, please feel free to use any part you wish.  If you feel there is something important missing from pyshortcuts, please let me know.  Cheers!

**Comment by kiwi0fruit** [comment]
@newville Icons and arguments sound good.

By the way: I was not aware about `pythonw` issue on macOS. Could you please test if [enaml-video-app](https://github.com/kiwi0fruit/enaml-video-app/tree/master/setup) example app works on macOS. The app creates it's own environment then bash script with `python -m enaml_video_app`. It uses Qt for Python so `pythonw` may be the issue (but may be it's still OK?).

If you do not feel like testing please share your thoughts about how conda based apps with their own environments and Qt should be handled.

**Comment by newville** [comment]
@kiwi0fruit  The need for using pythonw on MacOS seems to be unique to Anaconda builds of Python, and seems to affect wxPython.   See  https://github.com/ContinuumIO/anaconda-issues/issues/199 for reference.  I do not know that PyQt apps are *never* affected, but they appear to not be.  I also do not understand why different toolkits are treated differently.  

I have not tried installing your app.  Since you are already having users create and install into a miniconda environment,  I would recommend using conda constructor (https://github.com/conda/constructor) to build and distribute single-file installers for custom environments. This works very well for me. A tool like `pyshortcuts` can be used in the post-install process to create desktop shortcuts for the apps.

**Comment by kiwi0fruit** [comment]
And in order to have pythonw inside conda environment should I install a
special package like python.app?

**Comment by newville** [comment]
Yes, `pythonw` is installed with `conda install python.app`.

**Comment by kiwi0fruit** [comment]
Thanks!

**Comment by kiwi0fruit** [comment]
**TODO** Add to shortcutter:

* specify an icon,
* specify arguments,
* shortcut starts a program minimized (if OS allows),
  * I was not able to find a way to minimize terminal window on Wayland on Ubuntu so let it be visible.

**UPD** Dropped:

It's not that hard to provide the app with wrapper shell scripts that do all the work that should be done by entry point generators (in conda or setup.py) but unfortunately is not done by them. See [bash](https://github.com/kiwi0fruit/enaml-video-app/blob/master/enaml-video-app/scripts/enaml-video-appw) script.

So do not implement this:

* create shortcuts right to the python script (with pythonw support on macOS),
  * or may be create shell wrapper script first,
  * use `start "" pythonw.exe <...>`on Windows to start activation wrapper scripts for GUI (This would close terminal window. But I'm worried about deactivate script...),
  * or `python.exe <...>` inside batch script + set shortcut options to Run > Minimized (This would leave terminal window but minimized).

**Comment by newville** [comment]
@kiwi0fruit Can you perhaps say what features you have in shortcutter that are missing from pyshortcuts?  I think these might be "placing shortcuts in system resources like Start Menu" and "working with environments (pyenv or conda?)".  Is that correct?  Are there other important missing features?

**Comment by kiwi0fruit** [comment]
Start menu folder, custom folder, activate environment warppers, some error handling that is needed for using in setup.py - I like putting all that is needed to be done to the environment yaml file.

**Comment by kiwi0fruit** [comment]
Oh, and creating shortcuts for executables found in the PATH and specified by name only - without full path.

**Comment by newville** [comment]
Hm, OK. some thoughts:

 * *Start menu folder*:  I'm not sure how to do this or how to "tie to dock" or equivalent in a cross-platform way.  Do you?

*  *Custom folder*: pyshortcuts results are relocatable, and can go into a folder on the desktop that can later be moved.   I'm not sure there is a better approach than that.

* *activate environment warppers*" Wouldn't that need to be done from the python script?  I think desktop shortcuts cannot assume any PATH or environment except the login of the current user.

*  *some error handling that is needed for using in setup.py - I like putting all that is needed to be done to the environment yaml file*:  I'm not sure what that means

* *Oh, and creating shortcuts for executables found in the PATH and specified by name only - without full path*: I think the shortcut cannot assume an environment beyond the user login environment, so the shortcut-making script would have to search the current path for the script in question.  I could be persuaded, but sort of think that erring on the side of explicit is OK too.  That is, having "make shortcut" be formal and explicit doesn't seem like a big problem to me.

**Comment by kiwi0fruit** [comment]
I guess you should see code of the module to have answers to these questions... I would use shortcutter regardless and some day add features from TODO. As they are good fit to [enaml-video-app](https://github.com/kiwi0fruit/enaml-video-app).

**Comment by kiwi0fruit** [comment]
@newville I think it's not that hard to provide the app with wrapper shell scripts that do all the work that should be done by entry point generators (in conda or setup.py) but unfortunately is not done by them. See [bash](https://github.com/kiwi0fruit/enaml-video-app/blob/master/enaml-video-app/scripts/enaml-video-appw) script.

So I only would add icon, arguments and minimized options to shortcutter. Creating shortcuts for python scripts would be out of scope of the module.

**Comment by kiwi0fruit** [comment]
I'm closing this issue in favor of https://github.com/kiwi0fruit/shortcutter/issues/3

**Comment by kiwi0fruit** [comment]
I'm closing this issue in favor of https://github.com/kiwi0fruit/shortcutter/issues/5
